# Generated by Django 5.0.14 on 2026-05-25 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditoriaInmutable',
            fields=[
                ('id_auditoria', models.BigAutoField(primary_key=True, serialize=False)),
                ('numero_secuencia', models.PositiveBigIntegerField(unique=True)),
                ('hash_anterior', models.CharField(blank=True, max_length=64)),
                ('payload_json', models.JSONField()),
                ('hash_actual', models.CharField(max_length=64)),
                ('accion', models.CharField(max_length=80)),
                ('tipo_entidad', models.CharField(max_length=80)),
                ('id_entidad', models.CharField(max_length=80)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'auditoria_inmutable',
            },
        ),
    ]
