# Generated by Django 5.0.14 on 2026-05-25 15:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auditoria', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='auditoriainmutable',
            name='usuario_actor',
            field=models.ForeignKey(blank=True, db_column='id_usuario_actor', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='eventos_auditoria', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='auditoriainmutable',
            index=models.Index(fields=['tipo_entidad', 'id_entidad'], name='idx_audit_entidad'),
        ),
        migrations.AddIndex(
            model_name='auditoriainmutable',
            index=models.Index(fields=['numero_secuencia'], name='idx_audit_secuencia'),
        ),
    ]
