# Generated by Django 5.0.14 on 2026-05-25 15:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Apuesta',
            fields=[
                ('id_apuesta', models.BigAutoField(primary_key=True, serialize=False)),
                ('tipo_apuesta', models.CharField(choices=[('simple', 'Simple'), ('combinada', 'Combinada')], default='simple', max_length=16)),
                ('stake', models.DecimalField(decimal_places=4, max_digits=18)),
                ('odds_total', models.DecimalField(decimal_places=4, max_digits=18)),
                ('payout_potencial', models.DecimalField(decimal_places=4, max_digits=18)),
                ('estado_apuesta', models.CharField(choices=[('draft', 'Borrador'), ('accepted', 'Aceptada'), ('won', 'Ganada'), ('lost', 'Perdida'), ('void', 'Anulada'), ('cashed_out', 'Cash-out'), ('cancelled', 'Cancelada')], default='draft', max_length=16)),
                ('idempotency_key', models.CharField(blank=True, max_length=120, null=True, unique=True)),
                ('aceptada_en', models.DateTimeField(blank=True, null=True)),
                ('liquidada_en', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'apuestas',
            },
        ),
        migrations.CreateModel(
            name='DetalleApuesta',
            fields=[
                ('id_detalle_apuesta', models.BigAutoField(primary_key=True, serialize=False)),
                ('odds_snapshot', models.DecimalField(decimal_places=4, max_digits=18)),
                ('version_odds', models.PositiveIntegerField()),
                ('estado_detalle', models.CharField(choices=[('pending', 'Pendiente'), ('won', 'Ganado'), ('lost', 'Perdido'), ('void', 'Anulado')], default='pending', max_length=16)),
                ('resultada_en', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'detalles_apuesta',
            },
        ),
        migrations.CreateModel(
            name='LiquidacionApuesta',
            fields=[
                ('id_liquidacion', models.BigAutoField(primary_key=True, serialize=False)),
                ('resultado_liquidacion', models.CharField(choices=[('won', 'Ganada'), ('lost', 'Perdida'), ('void', 'Anulada'), ('cash_out', 'Cash-out')], max_length=16)),
                ('payout', models.DecimalField(decimal_places=4, max_digits=18)),
                ('liquidado_en', models.DateTimeField(default=django.utils.timezone.now)),
                ('observacion', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'liquidaciones_apuesta',
            },
        ),
    ]
