# Generated by Django 5.0.14 on 2026-05-25 15:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('apuesta', '0001_initial'),
        ('billetera', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='apuesta',
            name='transaction_bloqueo',
            field=models.ForeignKey(blank=True, db_column='transaction_id_bloqueo', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='apuestas_bloqueadas', to='billetera.transaccionledger'),
        ),
    ]
