# Generated by Django 5.0.14 on 2026-05-25 15:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('apuesta', '0002_initial'),
        ('billetera', '0001_initial'),
        ('deporte', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='apuesta',
            name='usuario',
            field=models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.PROTECT, related_name='apuestas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='detalleapuesta',
            name='apuesta',
            field=models.ForeignKey(db_column='id_apuesta', on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='apuesta.apuesta'),
        ),
        migrations.AddField(
            model_name='detalleapuesta',
            name='seleccion',
            field=models.ForeignKey(db_column='id_seleccion', on_delete=django.db.models.deletion.PROTECT, related_name='detalles_apuesta', to='deporte.seleccionmercado'),
        ),
        migrations.AddField(
            model_name='liquidacionapuesta',
            name='apuesta',
            field=models.OneToOneField(db_column='id_apuesta', on_delete=django.db.models.deletion.PROTECT, related_name='liquidacion', to='apuesta.apuesta'),
        ),
        migrations.AddField(
            model_name='liquidacionapuesta',
            name='liquidado_por',
            field=models.ForeignKey(blank=True, db_column='liquidado_por', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='liquidaciones_realizadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='liquidacionapuesta',
            name='transaction_liquidacion',
            field=models.ForeignKey(blank=True, db_column='transaction_id_liquidacion', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='liquidaciones_apuesta', to='billetera.transaccionledger'),
        ),
        migrations.AddIndex(
            model_name='apuesta',
            index=models.Index(fields=['usuario', 'estado_apuesta'], name='idx_apuesta_usuario_estado'),
        ),
        migrations.AddIndex(
            model_name='apuesta',
            index=models.Index(fields=['created_at'], name='idx_apuesta_created_at'),
        ),
        migrations.AddConstraint(
            model_name='apuesta',
            constraint=models.CheckConstraint(check=models.Q(('stake__gt', 0)), name='ck_apuesta_stake_positivo'),
        ),
        migrations.AddConstraint(
            model_name='apuesta',
            constraint=models.CheckConstraint(check=models.Q(('odds_total__gt', 1)), name='ck_apuesta_odds_total_mayor_uno'),
        ),
        migrations.AddConstraint(
            model_name='apuesta',
            constraint=models.CheckConstraint(check=models.Q(('payout_potencial__gte', models.F('stake'))), name='ck_apuesta_payout_potencial'),
        ),
        migrations.AddConstraint(
            model_name='apuesta',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('estado_apuesta', 'accepted'), _negated=True), ('transaction_bloqueo__isnull', False), _connector='OR'), name='ck_apuesta_accepted_con_bloqueo'),
        ),
        migrations.AddConstraint(
            model_name='detalleapuesta',
            constraint=models.CheckConstraint(check=models.Q(('odds_snapshot__gt', 1)), name='ck_detalle_odds_snapshot_mayor_uno'),
        ),
        migrations.AddConstraint(
            model_name='liquidacionapuesta',
            constraint=models.CheckConstraint(check=models.Q(('payout__gte', 0)), name='ck_liquidacion_payout_no_negativo'),
        ),
    ]
