# Generated by Django 5.0.14 on 2026-05-25 15:44

import cuentas.models
import django.contrib.auth.models
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('id_usuario', models.BigAutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(db_column='nombre_usuario', max_length=150, unique=True, verbose_name='nombre de usuario')),
                ('email', models.EmailField(db_column='correo', max_length=254, unique=True, verbose_name='correo')),
                ('password', models.CharField(db_column='password_hash', max_length=128, verbose_name='password hash')),
                ('rol', models.CharField(choices=[('PLAYER', 'Jugador'), ('ADMIN', 'Administrador'), ('OPERATOR', 'Operador')], default='PLAYER', max_length=20)),
                ('is_active', models.BooleanField(db_column='activo', default=True, verbose_name='activo')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'usuario',
                'verbose_name_plural': 'usuarios',
                'db_table': 'usuarios',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='PerfilJugador',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id_perfil', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombres', models.CharField(max_length=150)),
                ('apellidos', models.CharField(max_length=150)),
                ('dni', models.CharField(max_length=8, unique=True, validators=[django.core.validators.RegexValidator('^\\d{8}$', 'El DNI debe tener 8 digitos numericos.')])),
                ('fecha_nacimiento', models.DateField(validators=[cuentas.models.validate_minimum_age])),
                ('telefono', models.CharField(blank=True, max_length=30)),
                ('estado_cuenta', models.CharField(choices=[('pendiente_verificacion', 'Pendiente de verificacion'), ('verificado', 'Verificado'), ('bloqueado', 'Bloqueado'), ('autoexcluido', 'Autoexcluido')], default='pendiente_verificacion', max_length=32)),
                ('kyc_verificado_en', models.DateTimeField(blank=True, null=True)),
                ('usuario', models.OneToOneField(db_column='id_usuario', on_delete=django.db.models.deletion.CASCADE, related_name='perfil_jugador', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'perfil de jugador',
                'verbose_name_plural': 'perfiles de jugador',
                'db_table': 'perfiles_jugador',
            },
        ),
    ]
