# Generated by Django 5.0.14 on 2026-05-25 15:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialOdds',
            fields=[
                ('id_historial_odds', models.BigAutoField(primary_key=True, serialize=False)),
                ('odds', models.DecimalField(decimal_places=4, max_digits=18)),
                ('numero_version', models.PositiveIntegerField()),
                ('activa', models.BooleanField(default=True)),
                ('valido_desde', models.DateTimeField()),
                ('valido_hasta', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'historial_odds',
            },
        ),
        migrations.CreateModel(
            name='Mercado',
            fields=[
                ('id_mercado', models.BigAutoField(primary_key=True, serialize=False)),
                ('tipo_mercado', models.CharField(choices=[('1X2', '1X2'), ('OVER_UNDER', 'Over/Under'), ('BTTS', 'Ambos anotan'), ('HANDICAP', 'Handicap'), ('GOLEADOR_EXACTO', 'Goleador exacto')], max_length=32)),
                ('nombre', models.CharField(max_length=120)),
                ('estado_mercado', models.CharField(choices=[('abierto', 'Abierto'), ('suspendido', 'Suspendido'), ('cerrado', 'Cerrado'), ('liquidado', 'Liquidado'), ('anulado', 'Anulado')], default='abierto', max_length=16)),
                ('margen_operador', models.DecimalField(decimal_places=4, default=0, max_digits=8)),
                ('stake_minimo', models.DecimalField(decimal_places=4, max_digits=18)),
                ('stake_maximo', models.DecimalField(decimal_places=4, max_digits=18)),
                ('permite_in_play', models.BooleanField(default=False)),
                ('suspendido_hasta', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'mercados',
            },
        ),
        migrations.CreateModel(
            name='SeleccionMercado',
            fields=[
                ('id_seleccion', models.BigAutoField(primary_key=True, serialize=False)),
                ('codigo_seleccion', models.CharField(max_length=40)),
                ('nombre', models.CharField(max_length=120)),
                ('estado_seleccion', models.CharField(choices=[('activa', 'Activa'), ('suspendida', 'Suspendida'), ('ganadora', 'Ganadora'), ('perdedora', 'Perdedora'), ('anulada', 'Anulada')], default='activa', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'selecciones_mercado',
            },
        ),
        migrations.CreateModel(
            name='EventoDeportivo',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id_evento', models.BigAutoField(primary_key=True, serialize=False)),
                ('deporte', models.CharField(max_length=80)),
                ('competicion', models.CharField(max_length=120)),
                ('equipo_local', models.CharField(max_length=120)),
                ('equipo_visitante', models.CharField(max_length=120)),
                ('inicia_en', models.DateTimeField()),
                ('estado_evento', models.CharField(choices=[('programado', 'Programado'), ('en_vivo', 'En vivo'), ('finalizado', 'Finalizado'), ('suspendido', 'Suspendido'), ('anulado', 'Anulado')], default='programado', max_length=16)),
                ('marcador_local', models.PositiveSmallIntegerField(default=0)),
                ('marcador_visitante', models.PositiveSmallIntegerField(default=0)),
                ('resultado_confirmado', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'eventos_deportivos',
                'indexes': [models.Index(fields=['estado_evento', 'inicia_en'], name='idx_evento_estado_inicio')],
            },
        ),
        migrations.AddConstraint(
            model_name='eventodeportivo',
            constraint=models.CheckConstraint(check=models.Q(('equipo_local', models.F('equipo_visitante')), _negated=True), name='ck_evento_equipos_distintos'),
        ),
        migrations.AddField(
            model_name='historialodds',
            name='cambiado_por',
            field=models.ForeignKey(blank=True, db_column='cambiado_por', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='odds_modificadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mercado',
            name='evento',
            field=models.ForeignKey(db_column='id_evento', on_delete=django.db.models.deletion.CASCADE, related_name='mercados', to='deporte.eventodeportivo'),
        ),
        migrations.AddField(
            model_name='seleccionmercado',
            name='mercado',
            field=models.ForeignKey(db_column='id_mercado', on_delete=django.db.models.deletion.CASCADE, related_name='selecciones', to='deporte.mercado'),
        ),
        migrations.AddField(
            model_name='historialodds',
            name='seleccion',
            field=models.ForeignKey(db_column='id_seleccion', on_delete=django.db.models.deletion.CASCADE, related_name='historial_odds', to='deporte.seleccionmercado'),
        ),
        migrations.AddConstraint(
            model_name='mercado',
            constraint=models.CheckConstraint(check=models.Q(('stake_minimo__gt', 0)), name='ck_mercado_stake_minimo_positivo'),
        ),
        migrations.AddConstraint(
            model_name='mercado',
            constraint=models.CheckConstraint(check=models.Q(('stake_maximo__gte', models.F('stake_minimo'))), name='ck_mercado_stake_rango'),
        ),
        migrations.AddConstraint(
            model_name='mercado',
            constraint=models.CheckConstraint(check=models.Q(('margen_operador__gte', 0)), name='ck_mercado_margen_no_negativo'),
        ),
        migrations.AddConstraint(
            model_name='seleccionmercado',
            constraint=models.UniqueConstraint(fields=('mercado', 'codigo_seleccion'), name='uq_seleccion_codigo_por_mercado'),
        ),
        migrations.AddConstraint(
            model_name='historialodds',
            constraint=models.CheckConstraint(check=models.Q(('odds__gt', 1)), name='ck_odds_mayor_que_uno'),
        ),
        migrations.AddConstraint(
            model_name='historialodds',
            constraint=models.UniqueConstraint(fields=('seleccion', 'numero_version'), name='uq_odds_version_por_seleccion'),
        ),
        migrations.AddConstraint(
            model_name='historialodds',
            constraint=models.UniqueConstraint(condition=models.Q(('activa', True)), fields=('seleccion',), name='uq_odds_activa_por_seleccion'),
        ),
    ]
