# Generated by Django 5.0.14 on 2026-05-25 15:44

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Autoexclusion',
            fields=[
                ('id_autoexclusion', models.BigAutoField(primary_key=True, serialize=False)),
                ('tipo_autoexclusion', models.CharField(choices=[('temporal', 'Temporal'), ('indefinida', 'Indefinida')], max_length=16)),
                ('inicia_en', models.DateTimeField(default=django.utils.timezone.now)),
                ('finaliza_en', models.DateTimeField(blank=True, null=True)),
                ('activa', models.BooleanField(default=True)),
                ('motivo', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.CASCADE, related_name='autoexclusiones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'autoexclusiones',
            },
        ),
        migrations.CreateModel(
            name='LimiteJuegoResponsable',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id_limite', models.BigAutoField(primary_key=True, serialize=False)),
                ('periodo', models.CharField(choices=[('diario', 'Diario'), ('semanal', 'Semanal'), ('mensual', 'Mensual')], max_length=16)),
                ('limite_actual', models.DecimalField(decimal_places=4, max_digits=18)),
                ('limite_pendiente', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('pendiente_aplicar_en', models.DateTimeField(blank=True, null=True)),
                ('usuario', models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.CASCADE, related_name='limites_juego_responsable', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'limites_juego_responsable',
            },
        ),
        migrations.AddConstraint(
            model_name='autoexclusion',
            constraint=models.UniqueConstraint(condition=models.Q(('activa', True)), fields=('usuario',), name='uq_autoexclusion_activa_por_usuario'),
        ),
        migrations.AddConstraint(
            model_name='autoexclusion',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('finaliza_en__isnull', True), ('tipo_autoexclusion', 'indefinida')), models.Q(('finaliza_en__isnull', False), ('tipo_autoexclusion', 'temporal')), _connector='OR'), name='ck_autoexclusion_fecha_por_tipo'),
        ),
        migrations.AddConstraint(
            model_name='limitejuegoresponsable',
            constraint=models.UniqueConstraint(fields=('usuario', 'periodo'), name='uq_limite_usuario_periodo'),
        ),
        migrations.AddConstraint(
            model_name='limitejuegoresponsable',
            constraint=models.CheckConstraint(check=models.Q(('limite_actual__gte', 0)), name='ck_limite_actual_no_negativo'),
        ),
        migrations.AddConstraint(
            model_name='limitejuegoresponsable',
            constraint=models.CheckConstraint(check=models.Q(('limite_pendiente__isnull', True), ('limite_pendiente__gte', 0), _connector='OR'), name='ck_limite_pendiente_no_negativo'),
        ),
    ]
