# Generated by Django 5.0.14 on 2026-05-25 15:44

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cuenta',
            fields=[
                ('id_cuenta', models.BigAutoField(primary_key=True, serialize=False)),
                ('tipo_cuenta', models.CharField(choices=[('wallet_usuario', 'Wallet de usuario'), ('casa', 'Casa'), ('apuestas_pendientes', 'Apuestas pendientes'), ('bonos', 'Bonos')], max_length=32)),
                ('codigo', models.CharField(max_length=80, unique=True)),
                ('nombre', models.CharField(max_length=150)),
                ('estado', models.CharField(choices=[('activa', 'Activa'), ('bloqueada', 'Bloqueada'), ('cerrada', 'Cerrada')], default='activa', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'cuentas',
            },
        ),
        migrations.CreateModel(
            name='LedgerEntry',
            fields=[
                ('id_ledger_entry', models.BigAutoField(primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=4, max_digits=18)),
                ('direction', models.CharField(choices=[('DEBIT', 'Debito'), ('CREDIT', 'Credito')], max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'ledger_entries',
            },
        ),
        migrations.CreateModel(
            name='TransaccionLedger',
            fields=[
                ('transaction_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo_transaccion', models.CharField(choices=[('recarga', 'Recarga'), ('retiro', 'Retiro'), ('transferencia', 'Transferencia'), ('bloqueo_apuesta', 'Bloqueo de apuesta'), ('liquidacion', 'Liquidacion'), ('cash_out', 'Cash-out'), ('bono', 'Bono'), ('reversion', 'Reversion')], max_length=32)),
                ('idempotency_key', models.CharField(blank=True, max_length=120, null=True, unique=True)),
                ('tipo_referencia', models.CharField(blank=True, max_length=80)),
                ('id_referencia', models.CharField(blank=True, max_length=80)),
                ('estado', models.CharField(choices=[('pending', 'Pendiente'), ('completed', 'Completada'), ('failed', 'Fallida'), ('reversed', 'Revertida')], default='pending', max_length=16)),
                ('metadata_json', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'transacciones_ledger',
            },
        ),
    ]
