# Generated by Django 5.0.14 on 2026-05-25 15:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('billetera', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cuenta',
            name='usuario',
            field=models.ForeignKey(blank=True, db_column='id_usuario', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cuentas_contables', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ledgerentry',
            name='cuenta',
            field=models.ForeignKey(db_column='id_cuenta', on_delete=django.db.models.deletion.PROTECT, related_name='ledger_entries', to='billetera.cuenta'),
        ),
        migrations.AddField(
            model_name='transaccionledger',
            name='usuario',
            field=models.ForeignKey(blank=True, db_column='id_usuario', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transacciones_ledger', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ledgerentry',
            name='transaccion',
            field=models.ForeignKey(db_column='transaction_id', on_delete=django.db.models.deletion.PROTECT, related_name='entries', to='billetera.transaccionledger'),
        ),
        migrations.AddConstraint(
            model_name='cuenta',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('tipo_cuenta', 'wallet_usuario'), ('usuario__isnull', False)), models.Q(('tipo_cuenta', 'wallet_usuario'), _negated=True), _connector='OR'), name='ck_wallet_usuario_requiere_usuario'),
        ),
        migrations.AddIndex(
            model_name='ledgerentry',
            index=models.Index(fields=['transaccion', 'direction'], name='idx_ledger_tx_direction'),
        ),
        migrations.AddIndex(
            model_name='ledgerentry',
            index=models.Index(fields=['cuenta', 'created_at'], name='idx_ledger_cuenta_fecha'),
        ),
        migrations.AddConstraint(
            model_name='ledgerentry',
            constraint=models.CheckConstraint(check=models.Q(('amount__gt', 0)), name='ck_ledger_amount_positivo'),
        ),
    ]
