# Generated by Django 5.0.14 on 2026-05-28 07:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billetera', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='cuenta',
            index=models.Index(fields=['usuario', 'tipo_cuenta'], name='idx_cuenta_usuario_tipo'),
        ),
        migrations.AddIndex(
            model_name='cuenta',
            index=models.Index(fields=['tipo_cuenta', 'estado'], name='idx_cuenta_tipo_estado'),
        ),
        migrations.AddIndex(
            model_name='transaccionledger',
            index=models.Index(fields=['usuario', 'created_at'], name='idx_ledger_tx_usuario_fecha'),
        ),
        migrations.AddIndex(
            model_name='transaccionledger',
            index=models.Index(fields=['tipo_transaccion', 'estado'], name='idx_ledger_tx_tipo_estado'),
        ),
        migrations.AddIndex(
            model_name='transaccionledger',
            index=models.Index(fields=['tipo_referencia', 'id_referencia'], name='idx_ledger_tx_referencia'),
        ),
        migrations.AddConstraint(
            model_name='cuenta',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('tipo_cuenta__in', ['casa', 'apuestas_pendientes']), ('usuario__isnull', True)), models.Q(('tipo_cuenta__in', ['casa', 'apuestas_pendientes']), _negated=True), _connector='OR'), name='ck_cuentas_internas_sin_usuario'),
        ),
        migrations.AddConstraint(
            model_name='cuenta',
            constraint=models.UniqueConstraint(condition=models.Q(('tipo_cuenta', 'wallet_usuario')), fields=('usuario', 'tipo_cuenta'), name='uq_wallet_usuario_unica'),
        ),
        migrations.AddConstraint(
            model_name='transaccionledger',
            constraint=models.UniqueConstraint(condition=models.Q(models.Q(('tipo_referencia', ''), _negated=True), models.Q(('id_referencia', ''), _negated=True)), fields=('tipo_transaccion', 'tipo_referencia', 'id_referencia'), name='uq_ledger_tx_tipo_referencia'),
        ),
    ]
